# Generated by Django 5.1.1 on 2024-10-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code_bare',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='situation',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
