# Generated by Django 5.1.1 on 2024-10-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_teacher_student_num_alter_student_id_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='code_bare',
        ),
        migrations.AddField(
            model_name='student',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
