# Generated by Django 5.1.1 on 2024-10-03 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_remove_student_code_bare_student_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='confirmed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='situation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_student', to='Core.teacher'),
        ),
    ]
